window.timelineData=[
 {year:1939,category:"Physics",people:[
  {name:"Ernest Lawrence",photo:"photos/lawrence.png",lab:true,blurb:"Ernest Orlando Lawrence was the first faculty from UC Berkeley to receive a Nobel Prize, and set up the path for later Laureetes. Lawrence joined Berkeley faculty in 1928 when he was appointed as an Associate Professor in Physics and became a Professor two years later. At 29 years old, he was the youngest professor at Berkeley. In 1929, Lawrence invented the cyclotron, winning him the Nobel Prize in Physics. The cyclotron accelerated nuclear particles to very high velocities without the use of high voltages, and became the basis for radioactive elements and nuclear energy. In 1931, Lawrence founded the Berkeley Radiation Lab. Lawrence and Edward Teller founded the Lawrence Livermore Lab as a branch of the Radiation Lab to focus on nuclear weapons research during the Cold War. The Berkeley Radiation Lab is now known as The Lawrence Livermore National Laboratory, sitting above the UC Berkeley campus."}
 ]},
 {year:1949,category:"Chemistry",people:[
  {name:"William Giauque",photo:"photos/giaque.png",blurb:"William Giaque graduated from UC Berkeley College of Chemistry in 1920 and received his Ph.D. in chemistry and minor in physics in 1922. He became an Instructor of Chemistry in 1922 and was appointed as a Professor in 1934 by Professor Gilbert N. Lewis, the Dean at the time. Giaque would continue to be a professor for 40 years, and a Professor of Emeritus for 20 years after. Giaque’s research on the behaviour of matter at temperatures close to absolute zero awarded him the Nobel Prize in Chemistry in 1949. Giaque dedicated his life to groundbreaking research at UC Berkeley."}
 ]},
 {year:1951,category:"Chemistry",together:"The two won the Nobel Prize in Chemistry in 1951 for their co-discovery of plutonium and all further transuranium elements through element 102, including berkelium and californium.",people:[
  {name:"Glenn Seaborg",photo:"photos/seaborg.png",lab:true,blurb:"Glenn Seaborg received his Ph.D. in Chemistry from UC Berkeley in 1937. After researching under Professor Gilbert N. Lewis as his personal assistant, Seaborg became an instructor of chemistry in 1939 and a professor in 1945. From 1942 to 1946, Seaborg took a leave from UC Berkeley to work on transuranium elements at the Manhattan Project’s Metallurgical Laboratory at the University of Chicago. In 1946, Seaborg came back to Berkeley and led the nuclear chemical research at Radiation Lab (now Lawrence Livermore National Laboratory). In 1958, Seaborg was appointed as the second Chancellor of UC Berkeley. He served as Chancellor until President Kennedy appointed Seaborg the Chairman of the Atomic Energy Commission in 1961."},
  {name:"Edwin McMillan",photo:"photos/mcmillian.png",lab:true,blurb:"After Edwin McMillian received his Ph.D. in Chemistry from Princeton in 1932, he moved to UC Berkeley as a National Research Fellow. In 1934, McMillian began working under Ernest Lawrence at the Radiation Lab (now LLNL). In 1935, McMillian became an instructor in physics and a professor in 1946. In 1940, McMillian and Philip Abelson discovered neptunium using a particle accelerator to radiate uranium with neutrons. McMillian joined the Manhattan Project in 1942 and worked in Los Almost to research implosion methods."}
 ]},
 {year:1959,category:"Physics",together:"The two primarily researched atomic and nuclear physics and received the 1959 Nobel Prize in Physics for their discovery of the antiproton.",people:[
  {name:"Emilio Segrè",photo:"photos/segre.png",lab:true,blurb:"Emilio Segrè studied at the University of Rome and was appointed an Assistant Professor in 1932. In 1936 he was appointed Director of the Physics Laboratory at the University of Palermo. In 1938, Segrè came to Berkeley as a research associate at Radiation Lab (now LLNL) and later as a lecturer at the Physics Department. Segrè’s research focused on atomic spectroscopy, until 1934 when he began his research in nuclear physics with Professor Fermi on neutrons. Segrè was recruited by Robert J. Oppenheimer and served as a group leader in the Los Alamos Laboratory of the Manhattan Project."},
  {name:"Owen Chamberlain",photo:"photos/chamberlin.png",lab:true,blurb:"Owen Chamberlain is a Bay Area Native and was born in San Francisco. While pursuing his graduate degree at Berkeley, Chamberlain joined the Manhattan Project in Los Alamos under Segrè in 1942. Chamberlain finished his Ph.D. at University of Chicago and came back to Berkeley in 1948 to accept a teaching position and join the Radiation Lab. He continued to work with Segre, which led to their joint Nobel Prize. On campus, Chamberlain was also a supporter of the Free Speech Movement and advocated for minority enrollment at Berkeley. After World War 2, Chamberlain visited Hiroshima, and after witnessing the disaster, he became a human rights activist and was the founder of the nuclear freeze movement in the early 1980s."}
 ]},
 {year:1960,category:"Physics",people:[
  {name:"Donald Glaser",photo:"photos/glaser.png",lab:true,blurb:"Donald Glaser received his Ph.D. in physics and mathematics from California Institute of Technology in 1950, and soon moved to University of Michigan to start teaching and research in the Physics Department. In 1959, he came back to California and became a Professor of Physics at Berkeley. His research focused on elementary particles conducted at the Brookhaven National Laboratory in New York and the Lawrence Radiation Laboratory. Glaser received the 1960 Nobel Prize in Physics for inventing the bubble chamber, which allowed scientists to track the paths of electrons, protons and other charged particles after collisions. Soon after, Glaser began exploring the biotech side of his discovery and co-founded Cetus Corp in 1971, which developed the polymerase chain reaction to amplify DNA."}
 ]},
 {year:1961,category:"Chemistry",people:[
  {name:"Melvin Calvin",photo:"photos/calvin.png",lab:true,blurb:"Melvin Calvin completed his Ph.D. in Chemistry from the University of Minnesota in 1935. At the invitation of Professor Gilbert N. Lewis, Calvin started teaching at Berkeley in 1937 and became a Professor of Chemistry in 1947. Calvin supported Lewis and Professor G.E.K. Branch in organic molecules and chemistry research.Calvin became the founding Director of the Chemical Biodynamics Laboratory at Lawrence Berkeley Laboratory in 1960. The Lab was renamed to the Levin Calvin Laboratory in 1980 in his honor. Calvin received the 1961 Nobel Prize in Chemistry for this work at the lab on photosynthesis and research on the carbon dioxide assimilation in plants."}
 ]},
 {year:1968,category:"Physics",people:[
  {name:"Luis Alvarez",photo:"photos/alveraz.png",lab:true,blurb:"Luis Alvarez joined the Radiation Lab and became a professor at Berkeley in 1936, after completing his Ph.D. from University of Chicago. His early research in nuclear physics led to the investigation of neutron scatter and the magnetic moment of the neutron. During the war, Alveraz worked at MIT and the Metallurgical Laboratory of the University of Chicago from 1940 to 1944. In 1944 Robert J. Oppenheimer encouraged Alvarez to move to the Los Alamos Lab, where he developed the detonators for the plutonium bomb. Additionally, he flew as a scientific observer at the Almagordo and Hiroshima explosions. After the war, Alvarez came back to Berkeley, where he built and designed the Berkely’s 40-foot proton linear accelerator in 1947. He won the 1968 Nobel Prize in Physics for his continued research in elementary particle physics and his process of using the hydrogen bubble chamber. In 1980, Alvarez and other scientists hypothesized that dinosaurs went extinct due to an asteroid."}
 ]},
 {year:1983,category:"Economics",people:[
  {name:"Gerard Debreu",photo:"photos/debreu.png",blurb:"Gerard Debreu was born in France and began his college career at the start of WW2. Debreu studied mathematics at École Normale Supérieure, but, over his education, he became interested in the mathematical theory of economics. In 1949, Debreu received the Rockefeller scholarship that allowed him to visit universities in the US, including UC Berkeley. While visiting University of Chicago, Debreu was invited to be a Research Associate at the Cowles Commission for Research in Economics, where he went on the research the Pareto optima and the existence of a general economic equilibrium. In 1962, Debreu joined UC Berkeley. Debreu remained a visiting professor at a number of universities, but his research at Berkeley focused on the theory of measure spaces of economic agents. Debreu received the 1983 Nobel Prize in Economics for his analytical methods of economic theory and theory of general equilibrium. Debreu remained an active researcher and teacher at Berkeley even after his retirement in 1991."}
 ]},
 {year:1986,category:"Chemistry",people:[
  {name:"Yuan T. Lee",photo:"photos/lee.png",lab:true,blurb:"Yuen T. Lee received his masters in chemistry from National Tsinghua University and received his Ph.D. from Berkely in 1965. Lee began teaching at the University of Chicago and became a professor in 1973. In 1974, Lee returned to UC Berkeley as professor of chemistry and principal investigator at the Lawrence Berkeley Lab. In 1987, Lee served as the inaugural Co-Chair of the Chancellor’s Asian-American Affairs Committee. Lee won the 1986 Nobel Prize in Chemistry for his research in the dynamics of chemical elementary processes, with Dudley R. Herschbach and John C. Polanyi. In 1994, Lee returned to Taiwan to serve as President of Academia Sinica, a research institute in Taiwan. Lee remained engaged in Taiwanese progress, serving as a chair for the national committee for educational reform, community empowerment, and nonpartisan group to give advice on relations between Taiwan and China. Now, Lee serves as the President Emeritus at the Institute of Atomic and Molecular Sciences Academia Sinica, Taiwan."}
 ]},
 {year:1994,category:"Economics",people:[
  {name:"John Harsanyi",photo:"photos/harasanyi.png",blurb:"John Harsanyi was born in Hungary and grew up during WW2, where he had to serve in a forced labor unit in 1944. In 1947, Harsanyi received his Ph.D. in philosophy with minors in sociology and in psychology from the University of Budapest. Harsanyi went on to teach as a junior faculty member at the University Institute of Sociology, but in 1948 Harsanyi was forced to resign given his outspoken anti-Marxist ideals and the university's condemnment. Harsanyi and his wife fled to Australia, where he re-studied economics at the University of Sydney as his Hungarian degrees were not recognized. He received his masters in 1953 and in 1954 was appointed as a Lecturer in Economics at the University of Queensland. In 1956, Harsanyi received the Rockefeller Fellowship, which allowed him to move to Stanford to complete his Ph.D in economics under the guidance of the future 1972 Nobel Laureate Kenneth Arrow. Wanting to study game theory, Harsanyi found a position as a Professor of Economics at Wayne State University in Detroit. However, in 1964, he was appointed as a Visiting Professor and then Professor at the Business School and Department of Economics at Berkeley. Harsanyi helped advise the United States Arms Control and Disarmament Agency on its negotiations with the Soviet Union, but with his team, found that there was incomplete information. This inspired Harsanyi to then develop a mathematical procedure to convert an incomplete-information game into a complete-information game. Harsanyi received the 1994 Nobel Prize in Economics with John F. Nash and Reinhard Stein for this analysis of equilibria in the theory of non-cooperative games."}
 ]},
 {year:2000,category:"Economics",people:[
  {name:"Daniel McFadden",photo:"photos/mcfadden.png",blurb:"While still an undergrad, Daniel McFadden worked in the University of Minnesota Cosmic Ray Laboratory, where he designed and built an X-ray telescope and a very early transistorized computer for data processing. McFadden studied at the Ford Foundation’s Behavioral Science Training Program at Minnesota where he completed most of his Ph.D in economics. Under the Ford Foundation’s externship, McFadden worked under future 1972 Nobel Laureate Professor Kenneth Arrow and Professor Marc Nerlove. After completing his Ph.D in 1962, McFadden worked as a Mellon post-doctoral fellow at University of Pittsburgh, and then in 1963, he joined the faculty at Berkeley. In 1977, McFadden moved to the economics faculty at MIT and became the Director of the Statistics Research Center in 1986. In 1991, McFadden returned to Berkeley to establish the Econometrics Laboratory, a facility to improve statistical solutions in economics. McFadden won the 2000 Nobel Prize in Economics with James J. Heckman for their research in analyzing discrete choice and how individuals maximize utility. McFadden continues to be the E. Morris Cox Professor Emeritus of Economics at Berkeley."}
 ]},
 {year:2001,category:"Economics",people:[
  {name:"George Akerlof",photo:"photos/akerlof.png",blurb:"George Akerlof received his Ph.D. in Economics from MIT in 1966, where he found an interest in growth theory. Akerlof received an assistant professorship at Berkeley and in his first year, he wrote “Market for ‘Lemons,’” which was cited in his 2001 Nobel Prize in Economics. In 1967, Akerlof spent a year at the Indian Statistical Institute in New Delhi, where he learned about and researched the labor market. In 1973, Akerlof served as a Senior Economist at the Council of Economic Advisers. Akerlof became a professor at Berkeley in 1978. Akerlof’s research focused on unemployment and the labor market. Akerlof received the 2001 Nobel Prize in Economics for his analyses of markets with asymmetric information, along with A. Michael Spence and Joseph E. Stiglitz. Akerlof went on to teach public policy at McCourt College at Georgetown University, and recently retired."}
 ]},
 {year:2006,category:"Physics",people:[
  {name:"George Smoot",photo:"photos/smoot.png",lab:true,blurb:"George F. Smoot received his Ph.D. from MIT in 1970, soon after formative discoveries in astrophysics. Smoot was encouraged by 1968 Physics Nobel Prize winner, Professor Luis W. Alvarez, to accept a position at Berkeley and the Lawrence Lab where he worked on the NASA-funded High-Altitude Particle Physics Experiment. The project’s goal was to find evidence of the Big Bang, an emerging, yet favored explanation for the universe. In 1976, Smoot and his team built a differential microwave radiometer, which discovered that the universe was not rotating, but rather was expanding. In 1998, Smoot led a research group that went on to launch the COBE satellite, which discovered variations in radiation in different directions, which informed how stars form. Smoot received the 2006 Nobel Prize in Physics with John C. Mater for this discovery. Smoot became a professor in physics at Berkeley in 1994, and retired from both his research position at the Lawrence Livermore Lab and teaching in 2014."}
 ]},
 {year:2009,category:"Economics",people:[
  {name:"Oliver Williamson",photo:"photos/williamson.png",blurb:"Oliver Williamson received his MBA from Stanford in 1960 and his Ph.D. in Economics from Carnegie Mellon University in 1963. Williamson was awarded by the Ford Foundation to pursue his Ph.D. In 1963, Williamson accepted a teaching position at UC Berkeley. In 1966, Williamson served as the Special Economic Assistant to the Head of the Antitrust Division of the U.S. Department of Justice for a year. Williamson went on to teach at the University of Pennsylvania and Yale before returning to Berkeley in 1988. Williamson helped create a new field in the Economics Department and reshaped the Business and Public Policy curriculum in Haas. The Haas School established its highest faculty honor in his name: the Williamson Award. In 1995, Williamson served as Chair of the Academic Senate at Berkeley. Williamson’s research focused on transaction cost economics, organizational relationships, and antitrust. Williamson received the 2009 Nobel Prize in Economics for his analysis of economic governance within organizations and firms."}
 ]},
 {year:2011,category:"Physics",people:[
  {name:"Saul Perlmutter",photo:"photos/pearmutter.png",blurb:"Saul Perlmutter pursued his graduate studies at Berkeley and joined a research group led by Professor Richard Muller, where he focused on building a robotic-telescope supernova. Perlmutter completed his Ph.D. in 1986 at Berkeley but stayed post-doc to continue his research. In 1988, Perlmutter pursued one of the founding projects of Berkeley’s new Center for Particle Astrophysics, which was to build a wider field camera to search through thousands of galaxies at once. This project became known as The Supernova Cosmology Project, an international project which led to the discovery that the universe is expanding at an ever-increasing rate. Perlmutter received the 2011 Nobel Prize in Physics with Brian P. Schmidt and Adam G. Riess for their discovery of the accelerating expansion of the universe through observations of distant supernovae. Perlmutter served as the founding director of the Berkeley Institute for Data Science until 2023 and is currently the executive director of the Berkeley Center for Cosmological Physics."}
 ]},
 {year:2013,category:"Physiology or Medicine",people:[
  {name:"Randy Schekman",photo:"photos/schekman.png",blurb:"Randy Schekman found his passion for research early on during his undergraduate years at UCLA under Dan Ray in the Zoology Department. Schekman was admitted to 1959 Nobel Laureate’s, Arthur Kornberg, graduate program at Stanford. Schekman joined Berkeley faculty in 1979 and became a Professor in the Department of Molecular and Cell Biology in 1989. In 1991, Randy Schekman became an investigator at the Howard Hughes Medical Institute, a private, nonprofit biomedical research organization. In 2011, Schekman founded the Open Access journal, eLife, and served as Editor-in-Chief until 2019. Schekman received the 2013 Nobel Prize in Physiology or Medicine with James E. Rothman and Thomas C. Südhof for their discoveries of regulating vesicle transportation in cells. Schekman continues to teach Biology 1A every Fall at Berkeley."}
 ]},
 {year:2020,category:"Chemistry",people:[
  {name:"Jennifer Doudna",photo:"photos/doudna.png",lab:true,blurb:"Jennifer Doudna received her Ph.D. from Harvard Medical School in 1989 where she worked under 2009 Nobel Laureate Jack Szostak to research RNA. In 1991, Doudna moved to the University of Colorado Boulder to work under 1989 Nobel Laureate Tom Cech’s lab, researching the structure of RNA enzymes. In 1997, Doudna became a Howard Hughes Medical Institute investigator. In 2002, Doudna and her partner became professors at the Berkeley College of Chemistry and faculty at the Lawrence Livermore Lab. After receiving a call from UC Berkeley microbiologist Jillian Banfield introducing the idea of CRISPR, Banfield, Doudna and Mark Young from Montana State University organized the first international conference on CRISPR research. Doudna and Emmanuelle Charpentier used CRISPR to develop a method for genome editing, which won them the 2020 Nobel Prize in Chemistry. In 2014, Doudna founded, and still remains the president of, the Innovative Genomics Institute with Jonathan Weissman to research the potential of CRISPR. Doudna has served as Li Ka Shing Chancellor’s Chair at Berkeley since 2014. Doudna continues to teach Biology 1A every Spring at Berkeley."}
 ]},
 {year:2020,category:"Physics",people:[
  {name:"Reinhard Genzel",photo:"photos/genzel.png",blurb:"Reinhard Genzel completed his Ph.D. in Physics in 1978 from Max Planck Institute for Radio Astronomy in Germany. Genzel continued his research at the Harvard-Smithsonian Center for Astrophysics with James Moran. In 1980, Genzel joined Berkeley as a Miller Postdoctoral Fellow under 1964 Nobel Laureate Charles Townes, and then one year later as Associate Professor in the Physics Department. Genzel became a tenured professor at age 29 with the support of Townes. Genzel moved back to Germany in 1987 to become the director at the Max Planck Institute for Extraterrestrial Physics. Genzel received the 2020 Nobel Prize in Physics with Andrea Ghez for their discovery and proof of a black hole in the center of our Milky Way."}
 ]},
 {year:2021,category:"Economics",people:[
  {name:"David Card",photo:"photos/card.png",blurb:"David Card completed his Ph.D. in economics from Princeton University in 1983 and taught there until 1996. Card then moved to Berkeley to become a Professor of Economics. Card served as the Director of the Labor Studies Program at the National Bureau of Economic Research from 2012 to 2017. Card received the 2021 Nobel Prize in Economics for his research on the labor market and effects of minimum wages, immigration and education. Card continues to support Ph.D. students at Berkeley through a semesterly seminar."}
 ]},
 {year:2025,category:"Physics",people:[
  {name:"John Clarke",photo:"photos/clarke.png",lab:true,blurb:"John Clarke completed his Ph.D. in 1968 from Cambridge University. After a postdoctoral fellowship at UC Berkeley, he joined the Physics faculty at Berkeley and became a researcher at Lawrence Livermore Lab in 1969. In 2010, Clarke retired as a faculty senior scientist in the Materials Sciences Division. Clarke pioneered and developed an ultrasensitive detector called a superconducting quantum interference device (SQUID). Clarke received the 2025 Nobel Prize in Physics with Michel H. Devoret and John M. Martinis for demonstrating quantum mechanical properties on a macroscopic scale. Clarke is now a Professor Emeritus of the Graduate School in the Department of Physics."}
 ]},
 {year:2025,category:"Chemistry",people:[
  {name:"Omar Yaghi",photo:"photos/yaghi.png",blurb:"Omar Yaghi completed his Ph.D. in Chemistry at University of Illinois at Urbana-Champaign in 1990, and became a Postdoctoral Fellow at Harvard University. Yaghi was appointed the James and Neeltje Tretter Chair Professor of Chemistry in 2012. Clarke is the Founding Director of the Berkeley Global Science Institute and co-director and chief scientist of the Bakar Institute of Digital Materials for the Planet. Yaghi received the 2025 Nobel Prize in Chemistry with Richard Robson and Susumu Kitagawa for their development of metal–organic frameworks. While Yaghi was appointed as a University Professor in 2025, in July 2026, Yaghi announced his leave from Berkeley to Tsinghua University, where he will lead an AI-driven materials research centre."}
 ]}
];
